eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    instance:
      hostname: localhost

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**

        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/products/**


#server:
#  port: 8080